version: "3.9"

services:
  migrate:
    build:
      context: .
      network: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: task_server_migrate
    command: ["/migrator"]
    network_mode: host
    working_dir: /app
    depends_on:
      - db
    restart: "no"

  server:
    build:
      context: .
      network: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: task_server_server
    command: ["/subscriptions"]
    network_mode: host
    working_dir: /app
    depends_on:
      - migrate
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "5439:5432"
    container_name: task_server_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
