version: "3.9"

services:
  db:
    image: postgres:16
    container_name: subscription_db
    ports:
      - "${DB_PORT:-5439}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      retries: 5
      start_period: 5s

  migrate:
    build:
      context: .
    container_name: subscription_migrate
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ["/migrator"]
    working_dir: /app
    restart: "no"

  server:
    build:
      context: .
    container_name: subscription_server
    env_file:
      - .env
    environment:
      HTTP_SERVER_ADDRESS: :8080
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: ["/subscriptions"]
    working_dir: /app
    restart: unless-stopped

volumes:
  db_data: